name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==1.7.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Install Dependency
        run: poetry install --no-interaction --no-root
      - name: Lint with ruff
        run: poetry run ruff check --output-format=github .
      - name: Format with ruff
        run: poetry run ruff format --check .
      - name: Type checking with pyright
        run: poetry run pyright .
      - name: Test with pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: poetry run pytest --junitxml=junit/test-results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}