from contextlib import asynccontextmanager

import uvicorn
from fastapi import FastAPI

from shared.settings import settings
from web.core.alembic import async_autogenerated_migration


@asynccontextmanager
async def lifespan(app: FastAPI):
    await async_autogenerated_migration()
    yield


app = FastAPI(lifespan=lifespan)


@app.get("/")
def index():
    return {"Hello": "World!!!....!#!@#!@"}


if __name__ == "__main__":
    uvicorn.run(
        "main:app", host="0.0.0.0", port=8080, reload=settings.env == "development"
    )  # type: ignore
